export const countries = [
  { name: 'Afghanistan', code: '+93', iso: 'af', length: 9 },
  { name: 'Albania', code: '+355', iso: 'al', length: 9 },
  { name: 'Algeria', code: '+213', iso: 'dz', length: 9 },
  { name: 'Andorra', code: '+376', iso: 'ad', length: 6 },
  { name: 'Angola', code: '+244', iso: 'ao', length: 9 },
  { name: 'Argentina', code: '+54', iso: 'ar', length: 10 },
  { name: 'Armenia', code: '+374', iso: 'am', length: 8 },
  { name: 'Australia', code: '+61', iso: 'au', length: 9 },
  { name: 'Austria', code: '+43', iso: 'at', length: 10 },
  { name: 'Azerbaijan', code: '+994', iso: 'az', length: 9 },
  { name: 'Bahamas', code: '+1', iso: 'bs', length: 10 },
  { name: 'Bahrain', code: '+973', iso: 'bh', length: 8 },
  { name: 'Bangladesh', code: '+880', iso: 'bd', length: 10 },
  { name: 'Barbados', code: '+1', iso: 'bb', length: 10 },
  { name: 'Belarus', code: '+375', iso: 'by', length: 9 },
  { name: 'Belgium', code: '+32', iso: 'be', length: 9 },
  { name: 'Belize', code: '+501', iso: 'bz', length: 7 },
  { name: 'Benin', code: '+229', iso: 'bj', length: 8 },
  { name: 'Bhutan', code: '+975', iso: 'bt', length: 8 },
  { name: 'Bolivia', code: '+591', iso: 'bo', length: 8 },
  { name: 'Bosnia and Herzegovina', code: '+387', iso: 'ba', length: 8 },
  { name: 'Botswana', code: '+267', iso: 'bw', length: 8 },
  { name: 'Brazil', code: '+55', iso: 'br', length: 11 },
  { name: 'Brunei', code: '+673', iso: 'bn', length: 7 },
  { name: 'Bulgaria', code: '+359', iso: 'bg', length: 9 },
  { name: 'Burkina Faso', code: '+226', iso: 'bf', length: 8 },
  { name: 'Burundi', code: '+257', iso: 'bi', length: 8 },
  { name: 'Cambodia', code: '+855', iso: 'kh', length: 9 },
  { name: 'Cameroon', code: '+237', iso: 'cm', length: 9 },
  { name: 'Canada', code: '+1', iso: 'ca', length: 10 },
  { name: 'Cape Verde', code: '+238', iso: 'cv', length: 7 },
  { name: 'Central African Republic', code: '+236', iso: 'cf', length: 8 },
  { name: 'Chad', code: '+235', iso: 'td', length: 8 },
  { name: 'Chile', code: '+56', iso: 'cl', length: 9 },
  { name: 'China', code: '+86', iso: 'cn', length: 11 },
  { name: 'Colombia', code: '+57', iso: 'co', length: 10 },
  { name: 'Comoros', code: '+269', iso: 'km', length: 7 },
  { name: 'Congo', code: '+242', iso: 'cg', length: 9 },
  { name: 'Costa Rica', code: '+506', iso: 'cr', length: 8 },
  { name: 'Croatia', code: '+385', iso: 'hr', length: 9 },
  { name: 'Cuba', code: '+53', iso: 'cu', length: 8 },
  { name: 'Cyprus', code: '+357', iso: 'cy', length: 8 },
  { name: 'Czech Republic', code: '+420', iso: 'cz', length: 9 },
  { name: 'Denmark', code: '+45', iso: 'dk', length: 8 },
  { name: 'Djibouti', code: '+253', iso: 'dj', length: 6 },
  { name: 'Dominica', code: '+1', iso: 'dm', length: 10 },
  { name: 'Dominican Republic', code: '+1', iso: 'do', length: 10 },
  { name: 'Ecuador', code: '+593', iso: 'ec', length: 9 },
  { name: 'Egypt', code: '+20', iso: 'eg', length: 10 },
  { name: 'El Salvador', code: '+503', iso: 'sv', length: 8 },
  { name: 'Equatorial Guinea', code: '+240', iso: 'gq', length: 9 },
  { name: 'Eritrea', code: '+291', iso: 'er', length: 7 },
  { name: 'Estonia', code: '+372', iso: 'ee', length: 8 },
  { name: 'Ethiopia', code: '+251', iso: 'et', length: 9 },
  { name: 'Fiji', code: '+679', iso: 'fj', length: 7 },
  { name: 'Finland', code: '+358', iso: 'fi', length: 9 },
  { name: 'France', code: '+33', iso: 'fr', length: 9 },
  { name: 'Gabon', code: '+241', iso: 'ga', length: 7 },
  { name: 'Gambia', code: '+220', iso: 'gm', length: 7 },
  { name: 'Georgia', code: '+995', iso: 'ge', length: 9 },
  { name: 'Germany', code: '+49', iso: 'de', length: 11 },
  { name: 'Ghana', code: '+233', iso: 'gh', length: 9 },
  { name: 'Greece', code: '+30', iso: 'gr', length: 10 },
  { name: 'Grenada', code: '+1', iso: 'gd', length: 10 },
  { name: 'Guatemala', code: '+502', iso: 'gt', length: 8 },
  { name: 'Guinea', code: '+224', iso: 'gn', length: 9 },
  { name: 'Guyana', code: '+592', iso: 'gy', length: 7 },
  { name: 'Haiti', code: '+509', iso: 'ht', length: 8 },
  { name: 'Honduras', code: '+504', iso: 'hn', length: 8 },
  { name: 'Hungary', code: '+36', iso: 'hu', length: 9 },
  { name: 'Iceland', code: '+354', iso: 'is', length: 7 },
  { name: 'India', code: '+91', iso: 'in', length: 10 },
  { name: 'Indonesia', code: '+62', iso: 'id', length: 11 },
  { name: 'Iran', code: '+98', iso: 'ir', length: 10 },
  { name: 'Iraq', code: '+964', iso: 'iq', length: 10 },
  { name: 'Ireland', code: '+353', iso: 'ie', length: 9 },
  { name: 'Israel', code: '+972', iso: 'il', length: 9 },
  { name: 'Italy', code: '+39', iso: 'it', length: 10 },
  { name: 'Jamaica', code: '+1', iso: 'jm', length: 10 },
  { name: 'Japan', code: '+81', iso: 'jp', length: 10 },
  { name: 'Jordan', code: '+962', iso: 'jo', length: 9 },
  { name: 'Kazakhstan', code: '+7', iso: 'kz', length: 10 },
  { name: 'Kenya', code: '+254', iso: 'ke', length: 9 },
  { name: 'Kiribati', code: '+686', iso: 'ki', length: 8 },
  { name: 'Korea, North', code: '+850', iso: 'kp', length: 10 },
  { name: 'Korea, South', code: '+82', iso: 'kr', length: 10 },
  { name: 'Kuwait', code: '+965', iso: 'kw', length: 8 },
  { name: 'Kyrgyzstan', code: '+996', iso: 'kg', length: 9 },
  { name: 'Laos', code: '+856', iso: 'la', length: 10 },
  { name: 'Latvia', code: '+371', iso: 'lv', length: 8 },
  { name: 'Lebanon', code: '+961', iso: 'lb', length: 8 },
  { name: 'Lesotho', code: '+266', iso: 'ls', length: 8 },
  { name: 'Liberia', code: '+231', iso: 'lr', length: 8 },
  { name: 'Libya', code: '+218', iso: 'ly', length: 9 },
  { name: 'Liechtenstein', code: '+423', iso: 'li', length: 7 },
  { name: 'Lithuania', code: '+370', iso: 'lt', length: 8 },
  { name: 'Luxembourg', code: '+352', iso: 'lu', length: 9 },
  { name: 'Macedonia', code: '+389', iso: 'mk', length: 8 },
  { name: 'Madagascar', code: '+261', iso: 'mg', length: 9 },
  { name: 'Malawi', code: '+265', iso: 'mw', length: 9 },
  { name: 'Malaysia', code: '+60', iso: 'my', length: 9 },
  { name: 'Maldives', code: '+960', iso: 'mv', length: 7 },
  { name: 'Mali', code: '+223', iso: 'ml', length: 8 },
  { name: 'Malta', code: '+356', iso: 'mt', length: 8 },
  { name: 'Mauritania', code: '+222', iso: 'mr', length: 8 },
  { name: 'Mauritius', code: '+230', iso: 'mu', length: 7 },
  { name: 'Mexico', code: '+52', iso: 'mx', length: 10 },
  { name: 'Micronesia', code: '+691', iso: 'fm', length: 7 },
  { name: 'Moldova', code: '+373', iso: 'md', length: 8 },
  { name: 'Monaco', code: '+377', iso: 'mc', length: 8 },
  { name: 'Mongolia', code: '+976', iso: 'mn', length: 8 },
  { name: 'Montenegro', code: '+382', iso: 'me', length: 8 },
  { name: 'Morocco', code: '+212', iso: 'ma', length: 9 },
  { name: 'Mozambique', code: '+258', iso: 'mz', length: 9 },
  { name: 'Myanmar', code: '+95', iso: 'mm', length: 9 },
  { name: 'Namibia', code: '+264', iso: 'na', length: 9 },
  { name: 'Nepal', code: '+977', iso: 'np', length: 10 },
  { name: 'Netherlands', code: '+31', iso: 'nl', length: 9 },
  { name: 'New Zealand', code: '+64', iso: 'nz', length: 10 },
  { name: 'Nicaragua', code: '+505', iso: 'ni', length: 8 },
  { name: 'Niger', code: '+227', iso: 'ne', length: 8 },
  { name: 'Nigeria', code: '+234', iso: 'ng', length: 10 },
  { name: 'Norway', code: '+47', iso: 'no', length: 8 },
  { name: 'Oman', code: '+968', iso: 'om', length: 8 },
  { name: 'Pakistan', code: '+92', iso: 'pk', length: 10 },
  { name: 'Palau', code: '+680', iso: 'pw', length: 7 },
  { name: 'Panama', code: '+507', iso: 'pa', length: 8 },
  { name: 'Papua New Guinea', code: '+675', iso: 'pg', length: 8 },
  { name: 'Paraguay', code: '+595', iso: 'py', length: 9 },
  { name: 'Peru', code: '+51', iso: 'pe', length: 9 },
  { name: 'Philippines', code: '+63', iso: 'ph', length: 10 },
  { name: 'Poland', code: '+48', iso: 'pl', length: 9 },
  { name: 'Portugal', code: '+351', iso: 'pt', length: 9 },
  { name: 'Qatar', code: '+974', iso: 'qa', length: 8 },
  { name: 'Romania', code: '+40', iso: 'ro', length: 9 },
  { name: 'Russia', code: '+7', iso: 'ru', length: 10 },
  { name: 'Rwanda', code: '+250', iso: 'rw', length: 9 },
  { name: 'Samoa', code: '+685', iso: 'ws', length: 7 },
  { name: 'San Marino', code: '+378', iso: 'sm', length: 10 },
  { name: 'Saudi Arabia', code: '+966', iso: 'sa', length: 9 },
  { name: 'Senegal', code: '+221', iso: 'sn', length: 9 },
  { name: 'Serbia', code: '+381', iso: 'rs', length: 9 },
  { name: 'Seychelles', code: '+248', iso: 'sc', length: 7 },
  { name: 'Sierra Leone', code: '+232', iso: 'sl', length: 8 },
  { name: 'Singapore', code: '+65', iso: 'sg', length: 8 },
  { name: 'Slovakia', code: '+421', iso: 'sk', length: 9 },
  { name: 'Slovenia', code: '+386', iso: 'si', length: 8 },
  { name: 'Solomon Islands', code: '+677', iso: 'sb', length: 7 },
  { name: 'Somalia', code: '+252', iso: 'so', length: 8 },
  { name: 'South Africa', code: '+27', iso: 'za', length: 9 },
  { name: 'Spain', code: '+34', iso: 'es', length: 9 },
  { name: 'Sri Lanka', code: '+94', iso: 'lk', length: 9 },
  { name: 'Sudan', code: '+249', iso: 'sd', length: 9 },
  { name: 'Suriname', code: '+597', iso: 'sr', length: 7 },
  { name: 'Swaziland', code: '+268', iso: 'sz', length: 7 },
  { name: 'Sweden', code: '+46', iso: 'se', length: 9 },
  { name: 'Switzerland', code: '+41', iso: 'ch', length: 9 },
  { name: 'Syria', code: '+963', iso: 'sy', length: 9 },
  { name: 'Taiwan', code: '+886', iso: 'tw', length: 9 },
  { name: 'Tajikistan', code: '+992', iso: 'tj', length: 9 },
  { name: 'Tanzania', code: '+255', iso: 'tz', length: 9 },
  { name: 'Thailand', code: '+66', iso: 'th', length: 9 },
  { name: 'Togo', code: '+228', iso: 'tg', length: 8 },
  { name: 'Tonga', code: '+676', iso: 'to', length: 7 },
  { name: 'Trinidad and Tobago', code: '+1', iso: 'tt', length: 10 },
  { name: 'Tunisia', code: '+216', iso: 'tn', length: 8 },
  { name: 'Turkey', code: '+90', iso: 'tr', length: 10 },
  { name: 'Turkmenistan', code: '+993', iso: 'tm', length: 8 },
  { name: 'Tuvalu', code: '+688', iso: 'tv', length: 5 },
  { name: 'Uganda', code: '+256', iso: 'ug', length: 9 },
  { name: 'Ukraine', code: '+380', iso: 'ua', length: 9 },
  { name: 'United Arab Emirates', code: '+971', iso: 'ae', length: 9 },
  { name: 'United Kingdom', code: '+44', iso: 'gb', length: 10 },
  { name: 'United States', code: '+1', iso: 'us', length: 10 },
  { name: 'Uruguay', code: '+598', iso: 'uy', length: 8 },
  { name: 'Uzbekistan', code: '+998', iso: 'uz', length: 9 },
  { name: 'Vanuatu', code: '+678', iso: 'vu', length: 7 },
  { name: 'Vatican City', code: '+379', iso: 'va', length: 10 },
  { name: 'Venezuela', code: '+58', iso: 've', length: 10 },
  { name: 'Vietnam', code: '+84', iso: 'vn', length: 9 },
  { name: 'Yemen', code: '+967', iso: 'ye', length: 9 },
  { name: 'Zambia', code: '+260', iso: 'zm', length: 9 },
  { name: 'Zimbabwe', code: '+263', iso: 'zw', length: 9 },
];
